/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    sites: Site;
    pages: Page;
    tours: Tour;
    redirects: Redirect;
    authors: Author;
    partners: Partner;
    templates: Template;
    media: Media;
    'click-events': ClickEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'click-events': ClickEventsSelect<false> | ClickEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  /**
   * Normalized apex domain, no protocol or "www.", e.g. "streetfoodrome.com".
   */
  domain: string;
  /**
   * Hero sites: matches the folder under apps/web/src/sites/<slug>. Redirect sites: a stable internal identifier.
   */
  slug: string;
  type: 'hero' | 'redirect';
  niche: 'monument' | 'dayzia' | 'food' | 'cooking' | 'vehicle' | 'photo';
  /**
   * colorPrimary, colorAccent, colorBackground, colorForeground, fontHeading, fontBody, radius, heroStyle.
   */
  themeTokens:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  templateId?: (number | null) | Template;
  /**
   * If set and no template is chosen, this domain 301s to the hero instead of building a micro-site.
   */
  heroTargetSite?: (number | null) | Site;
  affiliateDefaults?: (number | Partner)[] | null;
  /**
   * GA4 measurement ID for this domain.
   */
  gaId?: string | null;
  /**
   * Search Console verification token for this domain.
   */
  gscToken?: string | null;
  status: 'draft' | 'live' | 'parked';
  language: 'en' | 'it';
  /**
   * Shared key linking an EN hero to its IT sibling for hreflang pairing.
   */
  hreflangGroup?: string | null;
  /**
   * Account this record belongs to.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  name: string;
  /**
   * Maps to packages/templates/src/registry.ts.
   */
  templateKey: 't1-monument' | 't2-dayzia' | 't3-food' | 't4-cooking' | 't5-vehicle' | 't6-photo';
  /**
   * Account this record belongs to.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  key: 'getyourguide' | 'viator' | 'tiqets' | 'civitatis';
  affiliateId: string;
  /**
   * Account this record belongs to.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  site: number | Site;
  slug: string;
  title: string;
  type: 'money' | 'support' | 'about' | 'legal';
  /**
   * Uniqueness enforced per-site by keywordMapCollisionCheck, not a DB constraint.
   */
  primaryKeyword: string;
  body?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            tours: (number | Tour)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'tourComparison';
          }
      )[]
    | null;
  heroImage?: (number | null) | Media;
  author?: (number | null) | Author;
  faqs?:
    | {
        question: string;
        /**
         * One quotable sentence — GEO/AI layer (M9).
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  featuredTours?: (number | Tour)[] | null;
  schemaType?:
    ('TouristAttraction' | 'TouristTrip' | 'Product' | 'FAQPage' | 'BreadcrumbList' | 'Course' | 'Service')[] | null;
  metaTitle: string;
  metaDesc: string;
  /**
   * Account this record belongs to.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Account this record belongs to.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  title: string;
  /**
   * The :slug in /go/:slug — must be globally unique across all Tours.
   */
  slug: string;
  partner: 'getyourguide' | 'viator' | 'tiqets' | 'civitatis';
  /**
   * Partner's own product/SKU id.
   */
  partnerProductId: string;
  /**
   * Raw partner deep link. Never render this directly — use /go/:slug.
   */
  affiliateUrl: string;
  priceBand?: ('€0-40' | '€40-80' | '€80-150' | '€150+') | null;
  /**
   * e.g. "3 hours".
   */
  duration?: string | null;
  city: string;
  /**
   * Tag array, e.g. "rome-food-tours-str", used to pull tours by niche into templates.
   */
  niche?: string[] | null;
  image?: (number | null) | Media;
  /**
   * Own-experience notes — feeds "is it worth it" verdict copy.
   */
  firstHandNotes?: string | null;
  /**
   * Account this record belongs to.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Account this record belongs to.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  site: number | Site;
  /**
   * Leading-slash path on this site, e.g. "/old-tour-page".
   */
  fromPath: string;
  toUrl: string;
  code: '301' | '302';
  /**
   * Account this record belongs to.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events".
 */
export interface ClickEvent {
  id: number;
  site: number | Site;
  tour?: (number | null) | Tour;
  /**
   * The /go/:slug that was clicked.
   */
  slug: string;
  partner?: ('getyourguide' | 'viator' | 'tiqets' | 'civitatis') | null;
  referrer?: string | null;
  userAgent?: string | null;
  /**
   * Account this record belongs to. Left blank on clicks logged by clickTracking.ts (an anonymous visitor action, no admin session) — backfilled for historical rows instead.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'click-events';
        value: number | ClickEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  domain?: T;
  slug?: T;
  type?: T;
  niche?: T;
  themeTokens?: T;
  templateId?: T;
  heroTargetSite?: T;
  affiliateDefaults?: T;
  gaId?: T;
  gscToken?: T;
  status?: T;
  language?: T;
  hreflangGroup?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  site?: T;
  slug?: T;
  title?: T;
  type?: T;
  primaryKeyword?: T;
  body?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        tourComparison?:
          | T
          | {
              heading?: T;
              tours?: T;
              id?: T;
              blockName?: T;
            };
      };
  heroImage?: T;
  author?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  featuredTours?: T;
  schemaType?: T;
  metaTitle?: T;
  metaDesc?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  partner?: T;
  partnerProductId?: T;
  affiliateUrl?: T;
  priceBand?: T;
  duration?: T;
  city?: T;
  niche?: T;
  image?: T;
  firstHandNotes?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  site?: T;
  fromPath?: T;
  toUrl?: T;
  code?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  avatar?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  affiliateId?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  templateKey?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events_select".
 */
export interface ClickEventsSelect<T extends boolean = true> {
  site?: T;
  tour?: T;
  slug?: T;
  partner?: T;
  referrer?: T;
  userAgent?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}